teams:
  - name: lfdt-staff
    maintainers:
      - jwagantall
      - ryjones
    members:
      - thelinuxfoundation
repositories:
  - name: .github
    teams:
      lfdt-staff: maintain
    visibility: public
  - name: governance
    teams:
      lfdt-staff: maintain
    visibility: public
