teams:
  - name: lfdt-staff
    maintainers:
      - jwagantall
      - ryjones
    members:
      - thelinuxfoundation
repositories:
  - name: .github
    visibility: public
  - name: governance
    visibility: public
